// Code generated by goctl. DO NOT EDIT!
// Source: trans.proto

package transclient

import (
	"context"

	"tcc/trans/trans"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdjustInfo = trans.AdjustInfo
	Response   = trans.Response

	Trans interface {
		TransOutTry(ctx context.Context, in *AdjustInfo, opts ...grpc.CallOption) (*Response, error)
		TransOutConfirm(ctx context.Context, in *AdjustInfo, opts ...grpc.CallOption) (*Response, error)
		TransOutCancel(ctx context.Context, in *AdjustInfo, opts ...grpc.CallOption) (*Response, error)
		TransInTry(ctx context.Context, in *AdjustInfo, opts ...grpc.CallOption) (*Response, error)
		TransInConfirm(ctx context.Context, in *AdjustInfo, opts ...grpc.CallOption) (*Response, error)
		TransInCancel(ctx context.Context, in *AdjustInfo, opts ...grpc.CallOption) (*Response, error)
	}

	defaultTrans struct {
		cli zrpc.Client
	}
)

func NewTrans(cli zrpc.Client) Trans {
	return &defaultTrans{
		cli: cli,
	}
}

func (m *defaultTrans) TransOutTry(ctx context.Context, in *AdjustInfo, opts ...grpc.CallOption) (*Response, error) {
	client := trans.NewTransClient(m.cli.Conn())
	return client.TransOutTry(ctx, in, opts...)
}

func (m *defaultTrans) TransOutConfirm(ctx context.Context, in *AdjustInfo, opts ...grpc.CallOption) (*Response, error) {
	client := trans.NewTransClient(m.cli.Conn())
	return client.TransOutConfirm(ctx, in, opts...)
}

func (m *defaultTrans) TransOutCancel(ctx context.Context, in *AdjustInfo, opts ...grpc.CallOption) (*Response, error) {
	client := trans.NewTransClient(m.cli.Conn())
	return client.TransOutCancel(ctx, in, opts...)
}

func (m *defaultTrans) TransInTry(ctx context.Context, in *AdjustInfo, opts ...grpc.CallOption) (*Response, error) {
	client := trans.NewTransClient(m.cli.Conn())
	return client.TransInTry(ctx, in, opts...)
}

func (m *defaultTrans) TransInConfirm(ctx context.Context, in *AdjustInfo, opts ...grpc.CallOption) (*Response, error) {
	client := trans.NewTransClient(m.cli.Conn())
	return client.TransInConfirm(ctx, in, opts...)
}

func (m *defaultTrans) TransInCancel(ctx context.Context, in *AdjustInfo, opts ...grpc.CallOption) (*Response, error) {
	client := trans.NewTransClient(m.cli.Conn())
	return client.TransInCancel(ctx, in, opts...)
}
